-- ============================================================
-- 004 — Adiciona campos e importa produtos do controle de estoque
-- Rodar no Supabase: SQL Editor → colar tudo → Run
-- Seguro para rodar mais de uma vez (ON CONFLICT ... DO UPDATE)
-- ============================================================

-- PASSO 1: Adicionar novas colunas à tabela products
ALTER TABLE products
  ADD COLUMN IF NOT EXISTS category     text,
  ADD COLUMN IF NOT EXISTS supplier     text,
  ADD COLUMN IF NOT EXISTS supplier_link text;

-- PASSO 2: Importar os 117 produtos do CSV
-- Mapeamento de categorias:
--   C=Cesta | FT=Fita | FL=Flor | VE=Vela | CHO=Chocolate
--   PERF=Perfume | HIDR=Hidratante | ALC=Sanitizante
--   SBM=Sabonete Líquido | GSBM=Sabonete Gel
--   EN=Envelope | CAR=Papel de Carta | SL=Selo/Tag | SD=Papel de Embrulho
--   MAN=Manta | COL=Colher | CAN=Caneca | ES=Espelho
--   BC=Body Cream | BW=Body Wash | BL=Body Lotion
--   SBB=Sabonete em Barra | TBW=Travel Body Wash | TBC=Travel Body Cream
--   TPSL/TPSS=Protetor Solar | TMIST=Travel Mist | PAPEL=Papel

INSERT INTO products (sku, name, stock_quantity, cost_price, sale_price, low_stock_threshold, active, category, supplier, supplier_link)
VALUES
  ('01',         'Cesta envelope ROSA com LISTRAS',                                                          4,  3.14,  3.24, 2, true, 'Cesta',             'Shein',            '41898497'),
  ('02',         'Cesta envelope MARSALA DOT',                                                               4,  2.60,  2.70, 2, true, 'Cesta',             'Shein',            '48571950'),
  ('03',         'Cesta retangular com alças PRETA',                                                         4,  3.41,  4.49, 2, true, 'Cesta',             'Shein',            '49291538'),
  ('04',         'Cesta retangular com alças ROSA',                                                          4,  3.41,  4.49, 2, true, 'Cesta',             'Shein',            '49435578'),
  ('05',         'Papel picado CHAMPAGNE',                                                                   1,  3.67,  3.70, 1, true,  NULL,               'Shein',            '23847714'),
  ('06',         'Fita floral com pérolas AMARELA',                                                          2,  1.84,  2.27, 1, true, 'Fita',              'Shein',            '23118343'),
  ('07',         'Flores tule BRANCAS',                                                                     30,  0.06,  0.09, 5, true, 'Flor',              'Shein',            '14707725'),
  ('08',         'Flores tule ROSA',                                                                        30,  0.06,  0.09, 5, true, 'Flor',              'Shein',            '14707865'),
  ('09',         'Vela Magnolia copo de vidro',                                                              5,  5.88,  7.13, 2, true, 'Vela',              'Shein',            '24244621'),
  ('010',        'Adesivo transparente THANK YOU',                                                          20,  0.09,  0.09, 5, true,  NULL,               'Shein',            '42430792'),
  ('011',        'Kit eye mask, scrunchie sleep, headband',                                                  5,  4.01,  4.43, 2, true,  NULL,               'Shein',            '13182887'),
  ('012',        'Tampa para canudo e pingente',                                                             1,  0.00,  0.00, 1, true,  NULL,               'Shein',            '47173428'),
  ('013',        'Espelho de bolsa ROSE GOLD',                                                               4,  2.52,  3.03, 2, true, 'Espelho',           'Shein',            '2758579'),
  ('014',        'Flor tulipa artificial BRANCA',                                                           10,  0.60,  1.62, 3, true, 'Flor',              'Shein',            '44754253'),
  ('015',        'Flor tulipa artificial ROSA',                                                             10,  0.62,  1.62, 3, true, 'Flor',              'Shein',            '44754253'),
  ('016',        'Envelope de cartas DARK GREEN',                                                            3,  0.28,  0.31, 1, true, 'Envelope',          'Shein',            '21793488'),
  ('017',        'Papel de carta VINTAGE com linhas (Shein)',                                               10,  0.28,  0.31, 3, true, 'Papel de Carta',    'Shein',            '21793488'),
  ('018',        'Selo brasão real VINTAGE',                                                                 3,  0.28,  0.31, 1, true, 'Selo/Tag',          'Shein',            '21793488'),
  ('019',        'Papel de embrulho VINTAGE KHAKI JORNAL',                                                  20,  0.25,  0.31, 5, true, 'Papel de Embrulho', 'Shein',            '15513449'),
  ('020',        'Kit de fazer selo de cera',                                                                1,  0.00,  0.00, 1, true,  NULL,               'Shein',            '31976022'),
  ('021',        'Espelho de bolsa GOLD CUSTOMIZADO',                                                        1,  0.00,  0.00, 1, true,  NULL,               'Shein',            '42935855'),
  ('022',        'Fita com pérolas tule ROSA',                                                               1,  3.12,  0.00, 1, true, 'Fita',              'Shein',            '14012103'),
  ('023',        'Pratinho de joias formato FLOR de ceramica Branco',                                        5,  2.77,  4.43, 2, true,  NULL,               'Shein',            '49547691'),
  ('024',        'Ramalhete mini ROSA',                                                                     18,  0.31,  0.32, 5, true, 'Flor',              'Shein',            '18154124'),
  ('025',        'Ramalhete mini DARK GREEN',                                                               20,  0.08,  0.09, 5, true, 'Flor',              'Shein',            '11771036'),
  ('026',        'Fita elegante de pano WHITE E PRETO',                                                      1,  2.00,  0.00, 1, true, 'Fita',              'Shein',            '50799373'),
  ('027',        'Bombom FERRERO ROCHER',                                                                   48,  0.38,  1.02,10, true, 'Chocolate',         'Costco',            NULL),
  ('028',        'NUTELLA TO GO',                                                                           16,  0.71,  2.45, 5, true, 'Chocolate',         'Costco',            NULL),
  ('029',        'Noir - Body Spray - Size: 3.7 oz / 104 g',                                                2,  6.43, 18.31, 1, true, 'Perfume',           'Bath & Body Works', NULL),
  ('030',        'Noir - Body Scrub - Size: 8oz / 226 g',                                                   1,  6.43, 20.47, 1, true, 'Hidratante',        'Bath & Body Works', NULL),
  ('031',        'Noir - Ultimate Hydration Body Cream - Size: 8 oz / 226 g',                               1,  6.43, 19.39, 1, true, 'Hidratante',        'Bath & Body Works', NULL),
  ('032',        'Champagne Toast - PocketBac Hand Sanitizer - Size: 1 fl oz / 29 mL',                      1,  1.80,  2.11, 1, true, 'Sanitizante',       'Bath & Body Works', NULL),
  ('033',        'A Thousand Wishes - PocketBac Hand Sanitizer - Size: 1 fl oz / 29 mL',                    1,  1.80,  2.11, 1, true, 'Sanitizante',       'Bath & Body Works', NULL),
  ('034',        'Lavender Vanilla - PocketBac Hand Sanitizer - Size: 1 fl oz / 29 mL',                     2,  1.80,  2.11, 1, true, 'Sanitizante',       'Bath & Body Works', NULL),
  ('035',        'Ocean - PocketBac Hand Sanitizer - Size: 1 fl oz / 29 mL',                                1,  1.80,  2.11, 1, true, 'Sanitizante',       'Bath & Body Works', NULL),
  ('036',        'Raspberries & Whipped Vanilla - PocketBac Hand Sanitizer - Size: 1 fl oz / 29 mL',        1,  1.80,  2.11, 1, true, 'Sanitizante',       'Bath & Body Works', NULL),
  ('037',        'Mahogany Teakwood - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',        1,  4.27,  8.59, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('038',        'Sweet Orange & Agave - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',     1,  4.27,  9.67, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('039',        'Champagne Toast - Cleansing Gel Hand Soap - Size: 8 fl oz / 236 mL',                      1,  4.27,  8.59, 1, true, 'Sabonete Gel',      'Bath & Body Works', NULL),
  ('040',        'Sweetest Song - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',            1,  4.27,  8.59, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('041',        'Champagne Toast - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',          1,  4.27,  8.59, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('042',        'Sunwashed Santal - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',         1,  4.27,  9.67, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('043',        'Fiji White Sands - Gentle & Clean Foaming Hand Soap - Size: 8.75 fl oz / 259 mL',         2,  4.27,  9.67, 1, true, 'Sabonete Líquido',  'Bath & Body Works', NULL),
  ('044',        'Mahogany Teakwood - Cleansing Gel Hand Soap - Size: 8 fl oz / 236 mL',                    1,  4.27,  8.59, 1, true, 'Sabonete Gel',      'Bath & Body Works', NULL),
  ('045',        'Envelope de carta OFF WHITE',                                                              6,  0.19,  0.29, 2, true, 'Envelope',          'TEMU',             'UK737379'),
  ('046',        'Tag WAX DOURADA "thank you" VINTAGE',                                                      6,  0.19,  0.29, 2, true, 'Selo/Tag',          'TEMU',             'UK737380'),
  ('047',        'Papel de carta VINTAGE com linhas (TEMU)',                                                20,  0.19,  0.29, 5, true, 'Papel de Carta',    'TEMU',             'UK737381'),
  ('048',        'Manta Blank WHITE - 100cm x 150cm',                                                        3,  9.32, 11.56, 1, true, 'Manta',             'Shein',            '38066538'),
  ('049',        'Colher Gold',                                                                              4,  0.53,  0.62, 2, true, 'Colher',            'Shein',            '9593377'),
  ('050',        'Caneca cerâmica BASE COR OCE - 8oz / 260ml',                                               6,  0.55,  8.64, 2, true, 'Caneca',            'TEMU',             'PH237287'),
  ('051',        'Fita de Cetim AZUL NAVY - 3.8cm x 9.1m',                                                  1,  4.53,  7.55, 1, true, 'Fita',              'JOANN',             NULL),
  ('052',        'Flor sempre viva',                                                                       100,  0.03,  0.15,20, true, 'Flor',              'TEMU',             'LK329113'),
  ('053',        'Cesta de PALHA M',                                                                         1,  8.63,  8.63, 1, true, 'Cesta',             'Home Goods',        NULL),
  ('SMVYXT0092', 'Boxes FERREIRO ROCHER',                                                                   20,  0.24,  6.54, 5, true,  NULL,               'TEMU',             'FR126714'),
  ('055',        'Caneca cerâmica WHITE VINTAGE - 14oz / 410ml',                                             4,  5.05,  6.80, 2, true, 'Caneca',            'Shein',            '47855295'),
  ('056',        'Fita de Cetim NAVY SATIN - 9mm x 9.1m',                                                   1,  1.94,  7.55, 1, true, 'Fita',              'JOANN',             NULL),
  ('057',        'Corda Sissal cor natural',                                                                  1,  2.46,  4.09, 1, true, 'Fita',              'JOANN',             NULL),
  ('058',        'Fita de Cetim NAVY SATIN - 3.2mm x 9.14m',                                                1,  1.08,  1.08, 1, true, 'Fita',              'Walmart',           NULL),
  ('059',        'Fita de Cetim ROSA CLARO - 3.2mm x 9.14m',                                                1,  1.08,  1.08, 1, true, 'Fita',              'Walmart',           NULL),
  ('060',        'Linha de crochê encerada OFF WHITE',                                                       1,  4.04,  5.39, 1, true, 'Fita',              'JOANN',             NULL),
  ('061',        'Fita de Cetim OFF WHITE - 1.6cm x 548cm',                                                  1,  1.40,  1.40, 1, true, 'Fita',              'Dollar Tree',       NULL),
  ('062',        'Fita de Cetim WHITE TRANSPARENTE - 1.6cm x 548cm',                                         1,  1.40,  1.40, 1, true, 'Fita',              'Dollar Tree',       NULL),
  ('063',        'Fita de Cetim WHITE - 3.2mm x 9.14m',                                                     1,  1.08,  1.08, 1, true, 'Fita',              'Walmart',           NULL),
  ('064',        'Fita de Cetim DOURADO METÁLICO - 3.2mm x 4.57m',                                          1,  1.05,  1.05, 1, true, 'Fita',              'Walmart',           NULL),
  ('065',        'Fita de Cetim ROSA CORAL - 16mm x 6.4m',                                                  1,  2.59,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('066',        'Fita de Cetim ROSA CORAL - 38mm x 6.4m',                                                  1,  4.53,  7.55, 1, true, 'Fita',              'JOANN',             NULL),
  ('067',        'Fita Natural PATRIOTA EUA - 3.8cm x 3.66m',                                               1,  3.88,  6.47, 1, true, 'Fita',              'JOANN',             NULL),
  ('068',        'Fita Natural Transparente OCRE - 9.5mm x 2.74m',                                          1,  1.29,  2.15, 1, true, 'Fita',              'JOANN',             NULL),
  ('069',        'Fita de Cetim ROSA CORAL - 57mm x 6.4m',                                                  1,  5.18,  8.63, 1, true, 'Fita',              'JOANN',             NULL),
  ('070',        'Fita de Cetim ROSA PINK - 16mm x 6.4m',                                                   1,  2.59,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('071',        'Fita de Cetim ROSA PINK - 38mm x 6.4m',                                                   1,  4.53,  7.55, 1, true, 'Fita',              'JOANN',             NULL),
  ('072',        'Fita de Cetim DOURADO - 38mm x 6.4m',                                                     1,  4.53,  7.55, 1, true, 'Fita',              'JOANN',             NULL),
  ('073',        'Fita Nylon WHITE TRANSPARENTE - 12.7mm x 9.1m',                                           1,  1.40,  3.22, 1, true, 'Fita',              'JOANN',             NULL),
  ('074',        'Fita Natural CORDA OFF WHITE - 38mm x 3.6m',                                              1,  2.59,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('075',        'Fita Natural CORDA OFF WHITE - 15.8mm x 3.6m',                                            1,  1.94,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('076',        'Fita Nylon WHITE TRANSPARENTE - 22mm x 3.6m',                                             1,  1.59,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('077',        'Fita Nylon WHITE TRANSPARENTE - 38.1mm x 4.5m',                                           1,  2.59,  4.31, 1, true, 'Fita',              'JOANN',             NULL),
  ('078',        'Tule com Gliter PRATA - 15.2cm x 2.74m',                                                  1,  1.40,  1.40, 1, true, 'Fita',              'Dollar Tree',       NULL),
  ('079',        'Sweet Orange & Agave 3-Wick Candle - Size: 14.5 oz / 411 g',                              1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('080',        'Fiji White Sands 3-Wick Candle - Size: 14.5 oz / 411 g',                                  1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('081',        'Sun-Drenched Linen 3-Wick Candle - Size: 14.5 oz / 411 g',                                1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('082',        'Champagne Toast - 3-Wick Candle - Size: 14.5 oz / 411 g',                                 1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('083',        'Sunwashed Santal - 3-Wick Candle - Size: 14.5 oz / 411 g',                                1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('084',        'Mahogany Teakwood Intense - 3-Wick Candle - Size: 14.5 oz / 411 g',                       1, 12.91, 29.11, 1, true, 'Vela',              'Bath & Body Works', NULL),
  ('085',        'Lavender Vanilla - Ultimate Hydration Body Cream - Size: 8 oz / 226 g',                   1,  0.00, 18.31, 1, true, 'Body Cream',        'Bath & Body Works', NULL),
  ('086',        'Lavender Vanilla - Moisturizing Body Wash - Size: 10 fl oz / 295 mL',                     1,  0.00, 18.31, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('087',        'At The Beach - Daily Nourishing Body Lotion - Size: 8 fl oz / 236 mL',                    1,  6.43, 17.23, 1, true, 'Body Lotion',       'Bath & Body Works', NULL),
  ('088',        'Butterfly - Body Lotion - Size: 8 fl oz / 236 mL',                                        1,  6.43, 17.23, 1, true, 'Body Lotion',       'Bath & Body Works', NULL),
  ('089',        'Platinum - Daily Nourishing Body Lotion - Size: 8 fl oz / 236 mL',                        1,  6.43, 18.31, 1, true, 'Body Lotion',       'Bath & Body Works', NULL),
  ('090',        'Champagne Toast - Daily Nourishing Body Lotion - Size: 8 fl oz / 236 mL',                 1,  6.43, 18.31, 1, true, 'Body Lotion',       'Bath & Body Works', NULL),
  ('091',        'Sweet Pea - Body Lotion - Size: 8 fl oz / 236 mL',                                        1,  6.43, 16.15, 1, true, 'Body Lotion',       'Bath & Body Works', NULL),
  ('092',        'At The Beach - Body Wash - Size: 10 fl oz / 295 mL',                                      1,  6.43, 17.23, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('093',        'Platinum - Body Wash - Size: 10 fl oz / 295 mL',                                          1,  6.43, 18.31, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('094',        'Butterfly - Body Wash - Size: 10 fl oz / 295 mL',                                         1,  6.43, 17.23, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('095',        'Champagne Toast - Body Wash - Size: 10 fl oz / 295 mL',                                   1,  6.43, 18.31, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('096',        'Sweet Pea - Body Wash - Size: 10 fl oz / 295 mL',                                         1,  6.43, 16.95, 1, true, 'Body Wash',         'Bath & Body Works', NULL),
  ('097',        'Ocean - Shea Butter Cleansing Bar - Size: 5 oz / 141.75 g',                               1,  3.51,  9.67, 1, true, 'Sabonete em Barra', 'Bath & Body Works', NULL),
  ('098',        'Lavender Vanilla - Shea Butter Cleansing Bar - Size: 5 oz / 141.75 g',                    4,  3.51,  9.67, 2, true, 'Sabonete em Barra', 'Bath & Body Works', NULL),
  ('099',        'Eucalyptus Spearmint - Shea Butter Cleansing Bar - Size: 5 oz / 141.75 g',                1,  3.51,  9.67, 1, true, 'Sabonete em Barra', 'Bath & Body Works', NULL),
  ('0100',       'Noir - Shea Butter Cleansing Bar - Size: 5 oz / 141.75 g',                                2,  3.51,  9.67, 1, true, 'Sabonete em Barra', 'Bath & Body Works', NULL),
  ('0101',       'Eucalyptus Spearmint - Travel Size Body Wash - Size: 2 fl oz / 59 mL',                    1,  3.51,  9.67, 1, true, 'Travel Body Wash',  'Bath & Body Works', NULL),
  ('0102',       'Lavender Vanilla - Travel Size Body Wash - Size: 2 fl oz / 88 mL',                        2,  3.51,  9.67, 1, true, 'Travel Body Wash',  'Bath & Body Works', NULL),
  ('0103',       'Noir - Travel Size Body Wash - Size: 3 fl oz / 88 mL',                                    2,  3.51,  9.67, 1, true, 'Travel Body Wash',  'Bath & Body Works', NULL),
  ('0104',       'A Thousand Wishes - Travel Size Body Wash - Size: 3 oz / 88 mL',                          1,  3.51,  9.67, 1, true, 'Travel Body Wash',  'Bath & Body Works', NULL),
  ('0105',       'Sweetest Song - Travel Size Body Wash - Size: 3 fl oz / 88 mL',                           1,  3.51,  9.67, 1, true, 'Travel Body Wash',  'Bath & Body Works', NULL),
  ('0106',       'Sweetest Song - Travel Size Body Cream - Size: 2.5 fl oz / 70 g',                         1,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0107',       'A Thousand Wishes - Travel Size Body Cream - Size: 2.5 oz / 70 g',                        2,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0108',       'Eucalyptus Spearmint - Travel Size Body Cream - Size: 2.5 oz / 70 g',                     2,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0109',       'Ocean - Travel Size Body Cream - Size: 2.5 oz / 70 g',                                    1,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0110',       'Noir - Travel Size Body Cream - Size: 2.5 oz / 70 g',                                     2,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0111',       'Lavender Vanilla - Travel Size Body Cream - Size: 2.5 oz / 70 g',                         3,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0112',       'Champagne Toast - Travel Size Body Cream - Size: 2.5 fl oz / 75 mL',                      2,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0113',       'At The Beach - Travel Size Body Cream - Size: 2.5 oz / 70 g',                             1,  3.51,  9.67, 1, true, 'Travel Body Cream', 'Bath & Body Works', NULL),
  ('0114',       'At The Beach - Travel Size SPF 50 Lotion - Size: 2.5 oz / 74 mL',                         1,  3.51, 13.99, 1, true, 'Protetor Solar',    'Bath & Body Works', NULL),
  ('0115',       'At The Beach - Travel Size SPF 50 Spray - Size: 1.8 fl oz / 53 mL',                       1,  3.51, 13.99, 1, true, 'Protetor Solar',    'Bath & Body Works', NULL),
  ('0116',       'Champagne Toast - Travel Size Fine Fragrance Mist - Size: 2.5 fl oz / 75 mL',             1,  3.51,  9.67, 1, true, 'Travel Mist',       'Bath & Body Works', NULL),
  ('0117',       'Epson Premium Presentation Paper MATTE - 8.5x11in, Double-sided, 50 Sheets',              2,  0.24,  0.24, 1, true, 'Papel',             'Amazon',            NULL)
ON CONFLICT (sku) DO UPDATE SET
  name              = EXCLUDED.name,
  stock_quantity    = EXCLUDED.stock_quantity,
  cost_price        = EXCLUDED.cost_price,
  sale_price        = EXCLUDED.sale_price,
  low_stock_threshold = EXCLUDED.low_stock_threshold,
  category          = EXCLUDED.category,
  supplier          = EXCLUDED.supplier,
  supplier_link     = EXCLUDED.supplier_link;

-- Verificação rápida
SELECT COUNT(*) AS total_importado FROM products;
